// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyzrpuDY-DvZgkCPuqI7uzghNrrL5Vo0',
    appId: '1:494576997890:web:4e8aa7d1c6b68b4b0af91b',
    messagingSenderId: '494576997890',
    projectId: 'flutter-video-audio-chat-3d937',
    authDomain: 'flutter-video-audio-chat-3d937.firebaseapp.com',
    storageBucket: 'flutter-video-audio-chat-3d937.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDJEg807DH_Hu-oAKSNiz6e-TZoNvu28',
    appId: '1:494576997890:android:c062a7b67d3ae7230af91b',
    messagingSenderId: '494576997890',
    projectId: 'flutter-video-audio-chat-3d937',
    storageBucket: 'flutter-video-audio-chat-3d937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFj-a1I437JB4oagJfVMvnD41QZzWqGPQ',
    appId: '1:494576997890:ios:f6df49f37b4074140af91b',
    messagingSenderId: '494576997890',
    projectId: 'flutter-video-audio-chat-3d937',
    storageBucket: 'flutter-video-audio-chat-3d937.appspot.com',
    iosClientId: '494576997890-mmibr2f4u8vkiog7apdr8oaervgr0odd.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioVideoCallFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFj-a1I437JB4oagJfVMvnD41QZzWqGPQ',
    appId: '1:494576997890:ios:f6df49f37b4074140af91b',
    messagingSenderId: '494576997890',
    projectId: 'flutter-video-audio-chat-3d937',
    storageBucket: 'flutter-video-audio-chat-3d937.appspot.com',
    iosClientId: '494576997890-mmibr2f4u8vkiog7apdr8oaervgr0odd.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioVideoCallFlutterApp',
  );
}